<a href="https://colab.research.google.com/github/adapasriram/Projectss/blob/main/NetflixRecommendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Good Morning Everyone! we will start in few minutes

# **Netflix Recommendation Engine**

**What are Recommender Systems?**

Recommender systems are algorithms designed to suggest relevant items to users. These systems are used in various domains such as e-commerce, streaming services, and social media. They enhance user experience by filtering vast amounts of information to deliver personalized content.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
netflix_dataset = pd.read_csv("/content/drive/MyDrive/Netflix Dataset/combined_data_1.txt.zip",header=None,names=["CustID","Rating"],usecols=[0,1])

In [ ]:
netflix_dataset

           CustID  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [ ]:
#if rating is NAN => value of custiD => mOVIEiD

In [ ]:
#MOVIE COUNT
#CustomerCount

In [ ]:
movie_count = netflix_dataset.isnull().sum().sum()
movie_count

4499

In [ ]:
customer_count = netflix_dataset["CustID"].nunique()
customer_count = customer_count - movie_count
customer_count

470758

In [ ]:
#how many people have rated movie as 1,2,3,4,5

In [ ]:
stars = netflix_dataset.groupby("Rating")["Rating"].agg(["count"])

In [ ]:
stars

          count
Rating
1.0     1118186
2.0     2439073
3.0     6904181
4.0     8085741
5.0     5506583

In [ ]:
netflix_dataset['Rating'].value_counts()

Rating
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [ ]:
movie_id = None
movie_np = []
for cust_id in netflix_dataset['CustID']:
  if ":" in cust_id:
    movie_id = int(cust_id.replace(":",""))
  movie_np.append(movie_id)

In [ ]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
netflix_dataset["MovieID"] = movie_np

In [ ]:
netflix_dataset

           CustID  Rating  MovieID
0              1:     NaN        1
1         1488844     3.0        1
2          822109     5.0        1
3          885013     4.0        1
4           30878     4.0        1
...           ...     ...      ...
24058258  2591364     2.0     4499
24058259  1791000     2.0     4499
24058260   512536     5.0     4499
24058261   988963     3.0     4499
24058262  1704416     3.0     4499

[24058263 rows x 3 columns]

In [ ]:
netflix_dataset.dropna(inplace=True)

In [ ]:
netflix_dataset

           CustID  Rating  MovieID
1         1488844     3.0        1
2          822109     5.0        1
3          885013     4.0        1
4           30878     4.0        1
5          823519     3.0        1
...           ...     ...      ...
24058258  2591364     2.0     4499
24058259  1791000     2.0     4499
24058260   512536     5.0     4499
24058261   988963     3.0     4499
24058262  1704416     3.0     4499

[24053764 rows x 3 columns]

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Rating   float64
 2   MovieID  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
netflix_dataset['CustID'] = netflix_dataset['CustID'].astype(int)

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   int64
 1   Rating   float64
 2   MovieID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
#pre filtering
#now we will remove the users that has less rated movies
#we will remove the movies that has been rated less in numbers

In [ ]:
#dataframe of movie_summary have all movie id and its counts

In [ ]:
movie_summary = netflix_dataset.groupby("MovieID")["Rating"].agg(["count"])

In [ ]:
movie_summary

         count
MovieID
1          547
2          145
3         2012
4          142
5         1140
...        ...
4495       614
4496      9519
4497       714
4498       269
4499       428

[4499 rows x 1 columns]

In [ ]:
#we will set up benchmark=>60 percentile of counts

In [ ]:
movie_benchmark = round(movie_summary['count'].quantile(0.6),0)
movie_benchmark

908.0

In [ ]:
#drop_movie_list => keep all the movies less than count of benchmark

In [ ]:
drop_movie_list = movie_summary[movie_summary['count']<movie_benchmark].index

In [ ]:
drop_movie_list

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='MovieID', length=2699)

In [ ]:
len(drop_movie_list)

2699

In [ ]:
4499-2699

1800

In [ ]:
#apply the same operation for customer as well, and find drop_cust_list

In [ ]:
cust_summary = netflix_dataset.groupby("CustID")["Rating"].agg(["count"])

In [ ]:
cust_summary

         count
CustID
6          153
7          195
8           21
10          49
25           4
...        ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62

[470758 rows x 1 columns]

In [ ]:
cust_benchmark = round(cust_summary['count'].quantile(0.6),0)
cust_benchmark

36.0

In [ ]:
drop_cust_list = cust_summary[cust_summary['count']<cust_benchmark].index

In [ ]:
drop_cust_list

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustID', length=282042)

In [ ]:
len(drop_cust_list)

282042

In [ ]:
#from netflix_dataset remove dropcustlist and dropmovielist

In [ ]:
print("The shape of data before triming:",netflix_dataset.shape)
netflix_dataset = netflix_dataset[~netflix_dataset['MovieID'].isin(drop_movie_list)]
netflix_dataset = netflix_dataset[~netflix_dataset['CustID'].isin(drop_cust_list)]
print("The shape of data after triming:",netflix_dataset.shape)

The shape of data before triming: (24053764, 3)
The shape of data after triming: (19695836, 3)

In [ ]:
df = pd.DataFrame({
    "Val" : [1,2,3,4,5]
})
df

   Val
0    1
1    2
2    3
3    4
4    5

In [ ]:
dropind = [1,2]

In [ ]:
df[~df['Val'].isin(dropind)]

   Val
2    3
3    4
4    5

#Model Building

In [ ]:
df_titles = pd.read_csv("/content/drive/MyDrive/Netflix Dataset/Copy of movie_titles.csv",encoding="ISO-8859-1",header=None,usecols=[0,1,2],names=["MovieID","Date","Movie Name"])

In [ ]:
df_titles

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#surpise
#it is a library in python used for building recommendation

In [ ]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [ ]:
!pip install scikit-surprise==1.1.4

Collecting scikit-surprise==1.1.4
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 4.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2581322 sha256=c292e15c3768124bb347d91f2a1be750e4633d23bc7b95522115428779cff6be
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [ ]:
import surprise
print(surprise.__version__)

1.1.4

In [ ]:
from surprise import Reader,Dataset,SVD

In [ ]:
model = SVD()

In [ ]:
reader = Reader()

In [ ]:
data = Dataset.load_from_df(netflix_dataset[["CustID","MovieID","Rating"]][:100000],reader)

In [ ]:
type(data)

surprise.dataset.DatasetAutoFolds

In [ ]:
from surprise.model_selection import cross_validate

In [ ]:
cross_validate(model,data,measures=["RMSE"],cv=3)

{'test_rmse': array([1.02141981, 1.01777892, 1.01478223]),
 'fit_time': (1.843268871307373, 1.346893310546875, 1.3359472751617432),
 'test_time': (0.40577077865600586, 0.4191465377807617, 0.41155147552490234)}

#Recommendation

In [ ]:
netflix_dataset

           CustID  Rating  MovieID
696        712664     5.0        3
697       1331154     4.0        3
698       2632461     3.0        3
699         44937     5.0        3
700        656399     4.0        3
...           ...     ...      ...
24056842  1055714     5.0     4496
24056843  2643029     4.0     4496
24056844   267802     4.0     4496
24056845  1559566     3.0     4496
24056846   293198     3.0     4496

[19695836 rows x 3 columns]

In [ ]:
df_titles

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#choosing specific user
user_Rating = netflix_dataset[netflix_dataset['CustID']==1331154]

In [ ]:
user_Rating

           CustID  Rating  MovieID
697       1331154     4.0        3
5178      1331154     4.0        8
31460     1331154     3.0       18
92840     1331154     4.0       30
224761    1331154     3.0       44
...           ...     ...      ...
23439584  1331154     4.0     4389
23546489  1331154     2.0     4402
23649431  1331154     4.0     4432
23844441  1331154     3.0     4472
23985561  1331154     4.0     4488

[253 rows x 3 columns]

In [ ]:
user_1331154 = df_titles.copy()

In [ ]:
user_1331154

       MovieID    Date                                         Movie Name
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17765    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766    17767  2004.0                  Fidel Castro: American Experience
17767    17768  2000.0                                              Epoch
17768    17769  2003.0                                        The Company
17769    17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
user_1331154["Estimated_Score"] = user_1331154['MovieID'].apply(lambda x: model.predict(1331154,x).est)

In [ ]:
user_1331154

,MovieID,Date,Movie Name,Estimated_Score
0,1,2003.0,Dinosaur Planet,3.581862
1,2,2004.0,Isle of Man TT 2004 Review,3.581862
2,3,1997.0,Character,3.654504
3,4,1994.0,Paula Abdul's Get Up & Dance,3.581862
4,5,2004.0,The Rise and Fall of ECW,3.872966
...,...,...,...,...
17765,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.581862
17766,17767,2004.0,Fidel Castro: American Experience,3.581862
17767,17768,2000.0,Epoch,3.581862
17768,17769,2003.0,The Company,3.581862
17769,17770,2003.0,Alien Hunter,3.581862

In [ ]:
user_1331154 = user_1331154.sort_values("Estimated_Score",ascending=False)

In [ ]:
user_1331154.head(10)

,MovieID,Date,Movie Name,Estimated_Score
24,25,1997.0,Inspector Morse 31: Death Is Now My Neighbour,3.934777
4,5,2004.0,The Rise and Fall of ECW,3.872966
27,28,2002.0,Lilo and Stitch,3.816061
17,18,1994.0,Immortal Beloved,3.810184
29,30,2003.0,Something's Gotta Give,3.776069
2,3,1997.0,Character,3.654504
0,1,2003.0,Dinosaur Planet,3.581862
11848,11849,1998.0,Earth,3.581862
11851,11852,1991.0,Return to the Blue Lagoon,3.581862
11850,11851,1946.0,The Yearling,3.581862