<a href="https://colab.research.google.com/github/adapasriram/US_HONEY_PRODUCTION/blob/main/PurchaseCasesStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/PurchaseDataNew.csv')
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,391,0,0,10.0,0,2,0.0,1.0,6.0,14.0,15200.0
1,1000004,284,1,4,7.0,1,2,1.0,1.0,8.0,17.0,19215.0
2,1000005,211,1,2,20.0,0,1,1.0,1.0,2.0,5.0,15665.0
3,1000006,363,0,5,9.0,0,1,0.0,5.0,8.0,14.0,5378.0
4,1000006,517,0,5,9.0,0,1,0.0,2.0,3.0,4.0,13055.0
...,...,...,...,...,...,...,...,...,...,...,...,...
80577,1004472,402,0,4,16.0,1,0,1.0,1.0,11.0,16.0,15175.0
80578,1004472,337,0,4,16.0,1,0,1.0,1.0,11.0,15.0,15430.0
80579,1004472,480,0,4,16.0,1,0,1.0,1.0,2.0,15.0,15387.0
80580,1004472,49,0,4,16.0,1,0,1.0,8.0,13.0,16.0,5861.0
80581,1004473,159,1,3,1.0,1,3,0.0,1.0,8.0,17.0,19253.0

In [5]:
df['Marital_Status'].unique()

array([0., 1.])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80582 entries, 0 to 80581
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     80582 non-null  int64
 1   Product_ID                  80582 non-null  int64
 2   Gender                      80582 non-null  int64
 3   Age                         80582 non-null  int64
 4   Occupation                  80582 non-null  float64
 5   City_Category               80582 non-null  int64
 6   Stay_In_Current_City_Years  80582 non-null  int64
 7   Marital_Status              80582 non-null  float64
 8   Product_Category_1          80582 non-null  float64
 9   Product_Category_2          80582 non-null  float64
 10  Product_Category_3          80582 non-null  float64
 11  Purchase                    80582 non-null  float64
dtypes: float64(6), int64(6)
memory usage: 7.4 MB

In [6]:
df['Age'].value_counts()

Age
2    32313
3    15908
1    15321
4     6365
5     5489
6     2829
0     2357
Name: count, dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.duplicated().sum()

np.int64(0)

Is the average purchase made by men of age 18-25 is 10000 .still it is same?

In [9]:
men_18_25 = df[(df['Age']==1) & (df['Gender']==1)]
men_18_25

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
37,1000022,487,1,1,15.0,0,4,0.0,1.0,8.0,17.0,12099.0
38,1000022,402,1,1,15.0,0,4,0.0,1.0,11.0,16.0,12098.0
39,1000022,358,1,1,15.0,0,4,0.0,2.0,4.0,15.0,9564.0
49,1000025,332,1,1,4.0,2,4,0.0,1.0,5.0,9.0,15361.0
50,1000025,71,1,1,4.0,2,4,0.0,1.0,2.0,15.0,15770.0
...,...,...,...,...,...,...,...,...,...,...,...,...
80491,1004446,180,1,1,18.0,1,1,1.0,1.0,2.0,15.0,11512.0
80492,1004446,394,1,1,18.0,1,1,1.0,1.0,15.0,18.0,11521.0
80493,1004446,23,1,1,18.0,1,1,1.0,1.0,2.0,13.0,3988.0
80494,1004446,75,1,1,18.0,1,1,1.0,5.0,8.0,17.0,5444.0
80564,1004465,209,1,1,4.0,0,1,1.0,2.0,3.0,4.0,3240.0

In [11]:
sample_size = 1100

In [10]:
men_18_25_sample = men_18_25.sample(sample_size, random_state=0)
men_18_25_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
38101,1001221,184,1,1,0.0,1,1,0.0,1.0,2.0,5.0,7943.0
20270,1004217,6,1,1,4.0,1,2,0.0,1.0,5.0,8.0,15811.0
59410,1005964,418,1,1,5.0,1,1,0.0,2.0,3.0,10.0,12882.0
48116,1000302,262,1,1,4.0,1,4,0.0,13.0,15.0,16.0,570.0
60975,1000742,411,1,1,0.0,2,1,0.0,1.0,2.0,15.0,11519.0
...,...,...,...,...,...,...,...,...,...,...,...,...
67798,1004104,96,1,1,16.0,2,1,0.0,1.0,2.0,13.0,11543.0
24313,1000273,82,1,1,4.0,1,2,1.0,1.0,2.0,5.0,15293.0
65041,1002847,234,1,1,4.0,0,3,0.0,1.0,11.0,15.0,7788.0
10361,1005283,323,1,1,2.0,2,1,1.0,5.0,8.0,14.0,5245.0
66325,1003471,485,1,1,4.0,0,1,0.0,2.0,3.0,15.0,10143.0

In [11]:
from statsmodels.stats.weightstats import ztest

z_stat,p_value = ztest(men_18_25_sample['Purchase'],value=10000)

In [12]:
p_value

np.float64(8.148630583437401e-24)

In [13]:
if p_value<0.05:
    print("We have to reject the null hypothesis, Average purchase made by men of Age group 18-25 is not 10000")
else:
    print("We failed to reject the null hypothesis,the average purchase made by men of Age group 18-25 is 10000.")

We have to reject the null hypothesis, Average purchase made by men of Age group 18-25 is not 10000

Is the average purchase made by men and women of age 18-25 same.

In [14]:
from scipy.stats import ttest_ind

In [16]:
data_men = df.loc[(df['Gender']==1) & (df['Age']==1)] #Selecting all male of 18-25 age category
data_women = df.loc[(df['Gender']==0) & (df['Age']==1)] #Selectin all females of 18-25 age category

In [17]:

data_men.shape

(11904, 12)

In [18]:
data_women.shape

(3417, 12)

In [19]:
# data_men_sample = 1100
# data_women_sample = 340
# A) 1100 B) 340 C) Average It's better to choose  a value between 1100 and 340
sample_size = 700
data_men_sample = data_men.sample(sample_size,random_state=34)
data_women_sample = data_women.sample(sample_size,random_state=34)

In [20]:
data_men_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
24199,1000214,260,1,1,20.0,2,1,0.0,2.0,5.0,14.0,6540.0
65042,1002847,70,1,1,4.0,0,3,0.0,1.0,5.0,17.0,7729.0
9055,1004535,82,1,1,19.0,1,1,0.0,1.0,2.0,5.0,15530.0
37672,1001018,149,1,1,4.0,0,4,0.0,1.0,2.0,14.0,19568.0
64147,1002239,416,1,1,10.0,0,0,0.0,1.0,6.0,15.0,4148.0
...,...,...,...,...,...,...,...,...,...,...,...,...
39190,1001733,213,1,1,14.0,1,0,1.0,6.0,8.0,13.0,12692.0
51573,1002010,75,1,1,4.0,1,0,0.0,5.0,8.0,17.0,3520.0
44352,1004346,380,1,1,17.0,1,2,1.0,1.0,2.0,9.0,15421.0
39976,1002097,371,1,1,5.0,2,0,0.0,1.0,15.0,16.0,12101.0
64629,1002559,355,1,1,10.0,2,2,0.0,1.0,8.0,17.0,7674.0

In [21]:
data_women_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
14071,1001125,92,0,1,4.0,1,2,0.0,6.0,8.0,16.0,16583.0
56965,1004699,113,0,1,0.0,2,4,0.0,1.0,2.0,16.0,12037.0
3043,1001561,162,0,1,4.0,2,2,0.0,10.0,13.0,16.0,18611.0
38985,1001638,241,0,1,17.0,1,3,0.0,10.0,15.0,16.0,18708.0
40749,1002557,391,0,1,19.0,2,3,0.0,1.0,6.0,14.0,15744.0
...,...,...,...,...,...,...,...,...,...,...,...,...
68383,1004399,137,0,1,4.0,2,1,1.0,4.0,8.0,9.0,2124.0
52115,1002258,122,0,1,4.0,1,4,0.0,8.0,14.0,17.0,9862.0
33916,1005061,522,0,1,19.0,2,2,1.0,3.0,4.0,5.0,2929.0
14295,1001232,146,0,1,4.0,2,2,0.0,1.0,2.0,5.0,18962.0
50679,1001605,225,0,1,0.0,1,1,0.0,11.0,13.0,16.0,4659.0

In [23]:
t_stat, p_value = ttest_ind(data_men_sample['Purchase'],data_women_sample['Purchase'],equal_var=False)


#equal_var = False
# Welch's t-test

In [22]:
p_value

np.float64(8.148630583437401e-24)

In [24]:
if p_value<0.05:
    print("We have to reject the null hypothesis, Average purchase made by both the groups is not same.")
else:
    print("We failed to reject the null hypothesis, Average purchase made by both the groups is same.")

We have to reject the null hypothesis, Average purchase made by both the groups is not same.

In [25]:
data_men_sample = data_men.sample(3,random_state=0)
data_men_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
38101,1001221,184,1,1,0.0,1,1,0.0,1.0,2.0,5.0,7943.0
20270,1004217,6,1,1,4.0,1,2,0.0,1.0,5.0,8.0,15811.0
59410,1005964,418,1,1,5.0,1,1,0.0,2.0,3.0,10.0,12882.0